source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.4'
gem 'webrick', '~> 1.8'

group :jekyll_plugins do
  gem 'jekyll-remote-theme'
  gem 'jekyll-seo-tag'
  gem 'jekyll-archives-v2'
  gem 'jekyll-email-protect'
  gem 'jekyll-feed'
  gem 'jekyll-imagemagick'
  gem 'jekyll-link-attributes'
  gem 'jekyll-paginate-v2'
  gem 'jekyll-scholar'
  gem 'jekyll-sitemap'
  gem 'jekyll-tabs'
  gem 'jekyll-toc'
  gem 'jemoji'
  gem 'classifier-reborn'
  gem 'css_parser'
  gem 'observer'
  gem 'ostruct'
  gem 'feedjira'
  gem 'httparty'
  gem 'nokogiri'
  gem 'rake'
end
